sudo: required
language: minimal

git:
  depth: 2

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/model
    - IMAGE_TAG=travis-ci-test
    - IMAGE=${IMAGE_REPO}:${IMAGE_TAG}
  matrix:
    - TARGET=test-travis
    - TARGET=flake8
    - TARGET=isort
    - TARGET=license

matrix:
  fast_finish: true

before_script:
  - docker login -u=decaftravis -p=${DOCKER_PASSWORD}
  - make setup

script:
  - docker pull ${IMAGE}
  - make ${TARGET}

stages:
  - build
  - test
  - push-tags
  - deploy-staging
    if: branch = kubernetes
  - deploy-prod
    if: branch = master

jobs:
  include:
    - stage: build
      script:
        - docker build --build-arg PIPENV_FLAGS="--deploy" -t ${IMAGE} .
        - docker push ${IMAGE}
    - stage: push-tags
      script:
        - docker pull ${IMAGE}
        - docker tag ${IMAGE} ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
        - docker tag ${IMAGE} ${IMAGE_REPO}:${TRAVIS_BRANCH}
        - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
        - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}
    - stage: deploy-staging
      script: skip
      deploy:
        provider: script
        script: ./scripts/travis_deploy.sh model-staging
    - stage: deploy-prod
      script: skip
      deploy:
        provider: script
        script: ./scripts/travis_deploy.sh model-prod

notifications:
  email: false
  slack:
    rooms:
      - ${SLACK_ACCOUNT}:${SLACK_TOKEN}#${SLACK_CHANNEL}
    on_success: never
    on_failure: always
    on_pull_requests: false
