sudo: required
language: minimal

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/simulations
    - IMAGE_TAG=${TRAVIS_BRANCH}

before_install:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh

install:
  - docker build -t ${IMAGE_REPO}:${TRAVIS_COMMIT::12} -t ${IMAGE_REPO}:${TRAVIS_BRANCH} .
  - make setup

script:
  - make black-check
  - make flake8
  - make isort
  - make license
  - make test-travis

before_deploy:
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: "Hi21BmbulHz9dw2P/P+dAVQAwq+trm4d8ZN+EALGzqjC++IfbR3lUgspilCe2MDwZ0KXl2KUbhEOn4ttREthY6090ENdxYCQpLHCq5GwKmR03V/HWGSSN9dLY+FZrIcPkhwmY/VhU9V+JcPMCa2eNOQjove6cgpseskPdBPc1gyITk4kEGSkHuvqcNLKXVStPaO7FFS0+DdY+VvWa8STqIRODBLk0cQHWbTLfM7pKLC0iNitEVS7ewOArxoB3qPKsIFKO+CsgecaFSQg2U0axdyZpyTNAB2g6OfNFGFtToOjdj0jA3BiQba7HuCahhztu5fWR2XrVTi0LpkGIhorRP5v1Tf31saq/dEoZ0thtncTydSXIoH20dOTOigzLpkHBGiAzR9SHaSADHFjfW6u5KJYXCbnTeU+e5GJxX8S9HH7o8D9BQiNwDF7ebqmZ5IFN6p1U5bK1gOWWmRfu7U7VEc/QEeFBi7vJeUNLfhOilwaQb9zX7Ai4mzxQdiLVFl6oKp5rgSvGGzdVKTkUzoRH0m9Vf+ZGlY2W6unv08/FqwxSCcOxbX6semm1x3eihmENzn/D4eG8Tp45NO81pZt7K8/fabk8ll63wbkGLpMLGrdFOoay4sRHL44Ghg9ClHeqo/6SuI6HYDwLcKNsx9uEdBAIRuMJU/DNCUcidEZzvk="
    on_success: change
    on_failure: change
    on_pull_requests: false
