sudo: required
language: minimal

git:
  depth: 2

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/model
    - IMAGE_TAG=travis-ci-test

before_install:
  - echo ${DOCKER_PASSWORD} | docker login -u=decaftravis --password-stdin

install:
  - docker build -t ${IMAGE_REPO}:${TRAVIS_COMMIT::12} -t ${IMAGE_REPO}:${TRAVIS_BRANCH} .
  - make setup

script:
  - make flake8
  - make isort
  - make license
  - make test-travis

before_deploy:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: HZd925GNCmHEtYolqwGK/TvNIUL30iVTcAHJZjBCJYzx/3MY20c8zxTnQhK0PiC82JNJxfjT2EZfgvs58Br85zaoDpqGZjnNuiTi0AVbC5n5qQBqTo8S9tV/RKyjotW0h9XlfLRIVagdNk9c/ncz1tHK2JWP23LjKnHPvLT+IdhbnpuQbAn2f+I38KH6D7j8I1B3+CqZo3/nPIR3d+RQPMS0r93HPmK/GFy5nZw8TI28hP3R2QbDDiUh1/AZu9HXY0NZIPMeTmzLgJ5Z7Mjdt9ynPqSh/EH9gVLBPxjVHOUISnPg8pm/qutmMv7GOE1UzySfKDyX20UJq8B2QBL4nfOHMZ81fqhwzWaPugHwBJgPPrvfXMbH+9sRD4zDFYHOkTKiHrj73oNmpNVZNXubyrOHCgS8FlAScUNgcm1jH/4zkdA66qmqhxGpVgAcF8eifez/SW87SDqgrRGl3n2ZAk1ls6V45L12njnuIOtpF02D8Pk8zd/w0caSJ0mWtlxxgSgQ3u16eqsv6X5a1FYvaG97ieYzsttGGEJ3jSP2uRcDvvnd+PRxo1PgJd/HaT9g7q6glG8V7921JiSorYQ3xzWIEb6eUWF3pbbkhRDbYu1Dbgv+zhqzlDiUphdLXKFp+X++WjKghqt022MqsVAwhZGQp8ZwWs6eS3Z7R3SBFTg=
    on_success: change
    on_failure: change
    on_pull_requests: false
