version: "2.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    links:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONASYNCIODEBUG=1
      - GENE_TO_REACTIONS_API=139.59.134.152
      - GENE_TO_REACTIONS_PORT=50053
      - ID_MAPPER_API=https://api.dd-decaf.eu/idmapping/query
      - REDIS_PORT_6379_TCP_ADDR=redis
    networks:
      default:
      iloop-net:
        aliases:
          - model-backend
  redis:
    image: redis
    ports:
      - 6379
    networks:
      - default

networks:
  iloop-net:
    external: true
