web:
  build: .
  dockerfile: Dockerfile
  ports:
    - 8000:8000
  links:
    - redis
  environment:
    - PYTHONUNBUFFERED=1
    - PYTHONASYNCIODEBUG=1
    - GENE_TO_REACTIONS_API
    - GENE_TO_REACTIONS_PORT
redis:
  image: redis
  ports:
    - 6379
