version: "2.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    links:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONASYNCIODEBUG=1
      - ANNOTATIONS_API=${ANNOTATIONS_API:-https://api-staging.dd-decaf.eu/annotation/genes}
      - ID_MAPPER_API=${ID_MAPPER_API:-https://api.dd-decaf.eu/idmapping/query}
      - REDIS_ADDR=${REDIS_ADDR:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
    networks:
      default:
      iloop-net:
        aliases:
          - model-backend
  redis:
    image: redis
    ports:
      - "${REDIS_PORT:-6379}"
    networks:
      - default

networks:
  iloop-net:
    external: true
