web:
  build: .
  dockerfile: Dockerfile
  ports:
    - 8000:8000
  links:
    - redis
  environment:
    - PYTHONUNBUFFERED=1
    - PYTHONASYNCIODEBUG=1
    - GENE_TO_REACTIONS_API=139.59.134.152
    - GENE_TO_REACTIONS_PORT=50053
    - ID_MAPPER_API=https://api.dd-decaf.eu/idmapping/query
redis:
  image: redis
  ports:
    - 6379
