apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-staging
spec:
  selector:
    matchLabels:
      app: model
      env: staging
  replicas: 1
  template:
    metadata:
      labels:
        app: model
        env: staging
    spec:
      containers:
      - name: web
        image: gcr.io/dd-decaf-cfbf6/model:devel
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: staging
        - name: SCRIPT_NAME
          value: /mcaffeine
        - name: REDIS_ADDR
          value: localhost
        - name: REDIS_PORT
          value: "6379"
        - name: MODEL_STORAGE_API
          value: https://api-staging.dd-decaf.eu/mstorage
        - name: ICE_API
          value: https://ice.dd-decaf.eu
        - name: IAM_API
          value: https://api-staging.dd-decaf.eu/iam
        - name: ICE_USERNAME
          valueFrom:
            secretKeyRef:
              name: model-staging
              key: ICE_USERNAME
        - name: ICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: model-staging
              key: ICE_PASSWORD
        - name: ID_MAPPER_API
          value: http://id-mapper-production/idmapping/query
        - name: prometheus_multiproc_dir
          value: /prometheus-client
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: model-staging
              key: SENTRY_DSN
        # Disabling sympy cache prevents significant memory leaks in the cobrapy stack
        - name: SYMPY_USE_CACHE
          value: "no"
        volumeMounts:
        - mountPath: /prometheus-client
          name: prometheus-client
        command: ["gunicorn", "-c", "gunicorn.py", "model.wsgi:app"]
        readinessProbe:
          httpGet:
            path: /mcaffeine/healthz
            port: 8000
          initialDelaySeconds: 5
        resources:
          requests:
            cpu: "1000m"
          limits:
            cpu: "6000m"
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "2000m"
      volumes:
      - name: prometheus-client
        emptyDir: {}
