apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: model-production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    # websocket support
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  tls:
  - hosts:
    - api.dd-decaf.eu
    secretName: decaf-tls
  rules:
  - host: api.dd-decaf.eu
    http:
      paths:
      - path: /model
        backend:
          serviceName: model-production
          servicePort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: model-staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - api-staging.dd-decaf.eu
    secretName: decaf-tls
  rules:
  - host: api-staging.dd-decaf.eu
    http:
      paths:
      - path: /mcaffeine
        backend:
          serviceName: model-staging
          servicePort: 80
