apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulations-staging
spec:
  selector:
    matchLabels:
      app: simulations
      env: staging
  replicas: 1
  template:
    metadata:
      labels:
        app: simulations
        env: staging
    spec:
      containers:
      - name: web
        image: gcr.io/dd-decaf-cfbf6/simulations:devel
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: staging
        - name: SCRIPT_NAME
          value: /simulations
        - name: MODEL_STORAGE_API
          value: http://model-storage-staging/model-storage
        - name: ICE_API
          value: http://ice
        - name: IAM_API
          value: http://iam-staging/iam
        - name: ICE_USERNAME
          valueFrom:
            secretKeyRef:
              name: simulations-staging
              key: ICE_USERNAME
        - name: ICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: simulations-staging
              key: ICE_PASSWORD
        - name: ID_MAPPER_API
          value: http://id-mapper-production/id-mapper
        - name: prometheus_multiproc_dir
          value: /prometheus-client
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: simulations-staging
              key: SENTRY_DSN
        volumeMounts:
        - mountPath: /prometheus-client
          name: prometheus-client
        readinessProbe:
          httpGet:
            path: /simulations/healthz
            port: 8000
          initialDelaySeconds: 5
        resources:
          requests:
            cpu: "1m"
          limits:
            cpu: "2000m"
      volumes:
      - name: prometheus-client
        emptyDir: {}
